// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpmXwQq7Qf_gbcLZeQZlczJmNNfCIgY5o',
    appId: '1:828570369213:web:5496d0b22b2bf9edc7cbd4',
    messagingSenderId: '828570369213',
    projectId: 'finhub-e5473',
    authDomain: 'finhub-e5473.firebaseapp.com',
    storageBucket: 'finhub-e5473.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuq3RwN9e3lDUYf3YOjdbdyXN0vPUdGQA',
    appId: '1:828570369213:android:e240472f9c75aa68c7cbd4',
    messagingSenderId: '828570369213',
    projectId: 'finhub-e5473',
    storageBucket: 'finhub-e5473.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpiwoMKk4Dmtl5wzlByOCaP8phgjH7ORk',
    appId: '1:828570369213:ios:a32f03e628722282c7cbd4',
    messagingSenderId: '828570369213',
    projectId: 'finhub-e5473',
    storageBucket: 'finhub-e5473.appspot.com',
    iosClientId: '828570369213-jc8a5ha5k6btn8aq7tmseoe2hj0ffb6s.apps.googleusercontent.com',
    iosBundleId: 'com.example.finhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpiwoMKk4Dmtl5wzlByOCaP8phgjH7ORk',
    appId: '1:828570369213:ios:a32f03e628722282c7cbd4',
    messagingSenderId: '828570369213',
    projectId: 'finhub-e5473',
    storageBucket: 'finhub-e5473.appspot.com',
    iosClientId: '828570369213-jc8a5ha5k6btn8aq7tmseoe2hj0ffb6s.apps.googleusercontent.com',
    iosBundleId: 'com.example.finhub',
  );
}
